config/routes.rb
AlexBook::Application.routes.draw do
  get "main/index"

  get "order/new"

  get "order/edit"

   root :to => 'main#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :isbn, :price, :publisher, :quantity, :title

  belongs_to :order

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :prepay, :total

  has_many :items
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :isbn, :price, :publisher, :title

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController


  def new
    if @order.nil?
      @order=Order.new
    end

    unless params[:pid].nil? or params[:quantity].nil?
      product=Product.find(params[:pid])
      @item=Item.new(:publisher=>product.publisher,:isbn=>product.isbn,:title=>product.title,:price=>product.price,:quantity=>params[:quantity])
      @item.save
      @order.items << @item
    end


  end




  def edit
  end


  def search
    @products=Product.where("upper(title) LIKE upper('%#{params[:title]}%')").where("upper(publisher) LIKE upper('%#{params[:publisher]}%')")

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlexBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<%= link_to "New" ,order_new_path %>
<%= link_to "Edit" ,order_edit_path %>

app/views/order/edit.html.erb
<h1>Order#edit</h1>
<p>Find me in app/views/order/edit.html.erb</p>

app/views/order/new.html.erb
<table border="1">

  <thead>
    <td>Title</td>
    <td>Publisher</td>
    <td>Price</td>
    <td>Quantity</td>
  </thead>

<% unless @order.items.nil? %>
    <% @order.items.each do |item| %>
        <tr>
        <td><%= item.title %></td>
        <td><%= item.publisher %></td>
        <td><%= item.price %></td>
        <td><%= item.quantity %></td>
        </tr>
    <% end %>
<% end %>


<tr>
  <td></td>
  <td></td>
  <td></td>
  <td><%= link_to "add", order_search_path %></td>
</tr>


</table>


<%= params %>
<br>
<%= @order.items %>

<br>

app/views/order/search.html.erb
<% @products.each do |product| %>

<h1><%= product.title %></h1>  <%= link_to "add" ,
                                           :action=>"new",
                                           :pid=>product.id,
                                           :quantity=>"1" %>

<% end %>